#cloud-config

groups:
  - ubuntu: [root, sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa yourkeyhere.... example@gmail.com

# Sets the GOPATH & downloads the demo payload
#cloud-config

runcmd:
  - apt update -y # Update package lists
  - sudo apt install -y python3-pip python3-venv curl # Install Python3 pip, venv, and curl
  - python3 -m venv flask-env # Create a Python virtual environment
  - . flask-env/bin/activate # Activate the virtual environment
  - pip install flask # Install Flask in the virtual environment
  - curl -o app.py https://raw.githubusercontent.com/Roshan-Ravindran/deploying-flask-application-using-terraform/refs/heads/master/flask/app.py # Download the app.py
  - mkdir -p templates # Create templates directory
  - curl -o templates/index.html https://raw.githubusercontent.com/Roshan-Ravindran/deploying-flask-application-using-terraform/refs/heads/master/flask/templates/index.html # Download the index.html template
  - chmod +x app.py # Make app.py executable
  - python3 app.py # Run the Flask app

